

POST http://localhost:3333/events
Content-Type: application/json
{
  "title": "NLW Unite",
  "details": "evento para programação",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/87e271be-7ec5-4630-9a5f-86d5d2b7fef1/attendees
Content-Type: application/json

{
  "name": "Manuel Ventura",
  "email": "example@email.com"
}

###

GET http://localhost:3333/events/87e271be-7ec5-4630-9a5f-86d5d2b7fef1